version: "3.7"

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    cap_add:
      - NET_ADMIN
    dns: 10.0.0.1
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "8443:8443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config: